apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: p2pool
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: P2Pool v3.10
          ports:
            - containerPort: 9332  # Adjust the port as per your p2pool configuration
          command:
            - "/bin/bash"
            - "-c"
            - |
              /path/to/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini
          volumeMounts:
            - name: monero-data
              mountPath: /data  # Adjust the mount path as per your requirements
      volumes:
        - name: monero-data
          persistentVolumeClaim:
            claimName: slave3-volume  # Adjust the PVC name as per your configuration
