apiVersion: v1
kind: Pod
metadata:
  name: p2pool-pod
  namespace: p2pool
spec:
  hostNetwork: true  # Use the host network
  containers:
    - name: p2pool-container
      image: SChernykh/p2pool
      command:
        - User
        - --host
        - 192.168.0.18
        - --wallet
        - 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
        - --mini
      volumeMounts:
        - name: monero-data
          mountPath: /data
        - name: monero-lmdb
          mountPath: /root/.bitmonero/lmdb
        - name: monero-monerod
          mountPath: /root/.monero/monerod  # Adjusted mount path
  volumes:
    - name: monero-data
      persistentVolumeClaim:
        claimName: slave3-volume
    - name: monero-lmdb
      hostPath:
        path: /home/worker3/p2pool/p2pool  # Adjusted directory path
        type: Directory
    - name: monero-monerod
      hostPath:
        path: /home/worker3/p2pool/p2pool  # Adjusted directory path
        type: File
