apiVersion: v1
kind: Service
metadata:
  name: p2pool-service
  namespace: default
spec:
  selector:
    app: p2pool
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # Change to LoadBalancer if you are using a cloud provider that supports it
