apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      nodeSelector:  # Specify node affinity here
        kubernetes.io/hostname: slave2  # Label of the target node
      containers:
        - name: p2pool-container
          image: busybox
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                mkdir -p /root/p2pool/p2pool
                chmod +x /root/p2pool/p2pool
                /root/p2pool/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini \
                --no-randomx
              done
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: p2pool
              mountPath: /root/p2pool/p2pool
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker2/p2pool/p2pool
            type: DirectoryOrCreate
  automountServiceAccountToken: false
