apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  hostNetwork: true
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - slave2
      containers:
        - name: p2pool-container
          image: busybox
          command: ["sh", "-c", "/root/p2pool/p2pool --host 74.56.241.2 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --no-randomx"]
          resources:
            limits:
              cpu: "4"
              memory: "5Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: p2pool-data
              mountPath: /root/p2pool
      volumes:
        - name: p2pool-data
          hostPath:
            path: /home/worker2/p2pool
            type: DirectoryOrCreate
  automountServiceAccountToken: false
  
