apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: busybox
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                mkdir -p /root/p2pool/p2pool
                chmod +x /root/p2pool/p2pool
                /root/p2pool/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --no-randomx
                sleep 10  # Add a sleep interval to reduce CPU usage
              done
          resources:
            limits:
              cpu: "1"  # Adjust CPU limit as needed
              memory: "2Gi"  # Adjust memory limit as needed
            requests:
              cpu: "0.5"  # Adjust CPU request as needed
              memory: "1Gi"  # Adjust memory request as needed
          volumeMounts:
            - name: p2pool
              mountPath: /root/p2pool/p2pool
          readinessProbe:
            exec:
              command:
                - "ls"
                - "/root/p2pool/p2pool"  # Change the command as needed to check readiness
            initialDelaySeconds: 30  # Adjust as needed
            periodSeconds: 10  # Adjust as needed
            timeoutSeconds: 5  # Adjust as needed
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker3/p2pool/p2pool
            type: Directory
  automountServiceAccountToken: true
