apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master
      hostNetwork: true  # Add this line to use the host's network
      containers:
        - name: p2pool-container
          image: busybox
          command: ["sh", "-c", "/root/p2pool/p2pool --host 74.56.241.2 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --rpc-login piclusterfarm:PiclusterFarmbitconnect44"]
          volumeMounts:
            - name: p2pool-data
              mountPath: /root/p2pool
      volumes:
        - name: p2pool-data
          hostPath:
            path: /home/manager/p2pool
            type: DirectoryOrCreate
  automountServiceAccountToken: false
