apiVersion: v1
kind: Pod
metadata:
  name: p2pool-exec
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3
  hostNetwork: true          
  containers:
  - name: p2pool-container
    image: busybox
    command:
    - /home/worker3/p2pool/p2pool --host 74.56.241.2 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --rpc-login piclusterfarm:PiclusterFarmbitconnect44
    volumeMounts:
    - name: xmrig-volume-worker3p2p
      mountPath: /
  volumes:
  - name: xmrig-volume-worker3p2p
    hostPath:
      path: /
         
         
