apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      hostNetwork: true  # Use the host network for the container
      nodeSelector:
        kubernetes.io/hostname: slave3
      containers:
        - name: p2pool-container
          image: busybox  # Use any base image since we'll use a custom script 
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                /home/worker3/p2pool/p2pool --host node.hacknoob.win --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini 
              done
          volumeMounts:
            - name: p2p-volume
              mountPath: /home/worker3/p2pool
      volumes:
        - name: p2p-volume
          hostPath:
            path: /home/worker3/p2pool
            type: DirectoryOrCreate
  automountServiceAccountToken: false

         
