apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: alpine:latest  # Using Alpine Linux as a lightweight base image
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                mkdir -p /root/p2pool/p2pool
                chmod +x /root/p2pool/p2pool
                /root/p2pool/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini \
                --no-randomx
              done
          resources:
            limits:
              cpu: "2"  # Reduced CPU limit
              memory: "2Gi"  # Reduced memory limit
            requests:
              cpu: "1"  # Reduced CPU request
              memory: "1Gi"  # Reduced memory request
          volumeMounts:
            - name: p2pool
              mountPath: /root/p2pool/p2pool
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker3/p2pool/p2pool
            type: DirectoryOrCreate  # Ensure the directory exists or create if not
  automountServiceAccountToken: false

