apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - slave2
      containers:
        - name: p2pool-container
          image: busybox
          command: ["sh", "-c", "/root/p2pool/p2pool --host 74.56.241.2 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --no-randomx"]
          resources:
            limits:
              cpu: "4"
              memory: "5Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          ports:
            - containerPort: 18080
            - containerPort: 37889
            - containerPort: 37888
            - containerPort: 3333
          volumeMounts:
            - name: p2pool-data
              mountPath: /root/p2pool
      volumes:
        - name: p2pool-data
          hostPath:
            path: /home/worker2/p2pool
            type: DirectoryOrCreate
  automountServiceAccountToken: false
  hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: p2pool-service
  namespace: p2pool
spec:
  type: NodePort
  selector:
    app: p2pool
  ports:
    - name: monero
      protocol: TCP
      port: 18080
      targetPort: 18080
      nodePort: 30001  # Choose a nodePort in the range 30000-32767
    - name: port37889
      protocol: TCP
      port: 37889
      targetPort: 37889
      nodePort: 30002  # Choose another nodePort
    - name: port37888
      protocol: TCP
      port: 37888
      targetPort: 37888
      nodePort: 30003  # Choose another nodePort
    - name: port3333
      protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30004  # Choose another nodePort
