apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apply-xmrig-space
spec:
  project: default
  source:
    repoURL: https://github.com/d3ceiver/p2pool.git
    targetRevision: HEAD
    path: /dev/xmrig/dev/  
  destination:
    server: https://kubernetes.default.svc  
    namespace: xmrig
  syncPolicy:
    automated:
      prune: true



