apiVersion: apps/v1
kind: Application
metadata:
  name: my-xmrig-deployer
spec:
  project: default
  source:
    repoURL: https://github.com/d3ceiver/p2pool.git
    targetRevision: HEAD
    path: dev/xmrig/dev
    chart: null
  destination:
    server: https://kubernetes.default.svc
    namespace: xmrig
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
