apiVersion: v1
kind: PersistentVolume
metadata:
  name: xmrig4-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/xmrig4-data  # Update this with the actual path on your node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xmrig4-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Should match the capacity in PV definition
