apiVersion: v1
kind: PersistentVolume
metadata:
  name: xmrig2-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/worker2/xmrig/build/  # Update this with the actual path on your node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xmrig2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Should match the capacity in PV definition
