apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig4
  name: xmrig-deployment4
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xmrig4
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave4
      containers:
        - name: xmrig-container4
          image: busybox  # Use any base image since we'll use a custom script
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                /xmrig/build/xmrig -o gulf.moneroocean.stream:80 -u 87T57vEfgmKevdUuXwsjZGYpZ8FUR5LuuZA8BGG9sQ91hUbaqRh7HywdxhKQcqvqbsaPuZktbBzPy5cwPpXtJh275TpS7U5 -p piD3ceiver
              done
          resources:
            limits:
              cpu: "2"
              memory: "5Gi"
            requests:
              cpu: "2"
              memory: "5Gi"
          volumeMounts:
            - name: worker4-data
              mountPath: /home/worker4/xmrig/build
      volumes:
        - name: worker4-data
          hostPath:
            path: /home/worker4/xmrig/build
            type: DirectoryOrCreate
