apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-runner-master
  namespace: miners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-runner-master
  template:
    metadata:
      labels:
        app: xmrig-runner-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: master

      containers:
      - name: xmrig
        image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            set -e
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -q
            apt-get install -y --no-install-recommends libhwloc-dev libssl-dev libuv1-dev ca-certificates
            chmod +x /home/manager/xmrig || true
            echo "Starting XMRig on node master"
            exec /home/manager/xmrig/build/xmrig 
        volumeMounts:
        - name: xmrig-bin
          mountPath: /home/manager/xmrig/build/

      volumes:
      - name: xmrig-bin
        hostPath:
          path: /home/manager/xmrig/build/
          type: Directory
