apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave2
  containers:
  - name: xmrig-container-2
    image: busybox
    command:
    - /home/worker2/xmrig/build/xmrig
    - -t
    - "3"
    - -o
    - node.hacknoob.win:3333
    - -u
    - slave2
    volumeMounts:
    - name: xmrig-volume-2
      mountPath: /
  volumes:
  - name: xmrig-volume-2
    hostPath:
      path: /
