apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-master
  namespace: miners
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"xmrig-exec-master","namespace":"miners"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"xmrig-exec-master"}},"template":{"metadata":{"labels":{"app":"xmrig-exec-master"}},"spec":{"containers":[{"name":"xmrig-container","image":"busybox","command":["/home/manager/xmrig/build/xmrig"],"volumeMounts":[{"name":"xmrig-volume","mountPath":"/"}]}],"volumes":[{"name":"xmrig-volume","hostPath":{"path":"/"}}]}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-exec-master
  template:
    metadata:
      labels:
        app: xmrig-exec-master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - master
      containers:
        - name: xmrig-container
          image: busybox
          imagePullPolicy: Always
          command:
            - /home/manager/xmrig/build/xmrig
          volumeMounts:
            - name: xmrig-volume
              mountPath: /
      volumes:
        - name: xmrig-volume
          hostPath:
            path: /
