apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave2
  containers:
  - name: xmrig-container-2
    image: busybox
    command:
    - /home/worker2/xmrig/build/xmrig
    - -t
    - "4"
    - -o
    - proxy.hacknoob.win:5552
    - -u
    - slave2+1500
    - -a
    - rx/0
    - --cpu-no-yield
    - --randomx-1gb-pages
    - --nicehash
    volumeMounts:
    - name: xmrig-volume-2
      mountPath: /
  volumes:
  - name: xmrig-volume-2
    hostPath:
      path: /
