apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-master
  namespace: miners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-exec-master
  template:
    metadata:
      labels:
        app: xmrig-exec-master
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - master
      containers:
        - name: xmrig
          image: ubuntu:22.04
          securityContext:
            privileged: true
          command:
            - /host/home/manager/xmrig/build/xmrig
          volumeMounts:
            - name: xmrig-root
              mountPath: /host
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    apt update && \
                    apt install -y libssl3 libhwloc15 && \
                    echo "Libraries installed."
      volumes:
        - name: xmrig-root
          hostPath:
            path: /
            type: Directory
