apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig-deployment
  namespace: xmrig
spec:
  replicas: 4  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - xmrig
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - xmrig
              topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - image: rcmelendez/xmrig:6.16.2
          name: xmrig
          command: ["xmrig"]
          args: ["-c", "/xmrig/etc/config.json"]
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "1"
          volumeMounts:
            - name: config-volume
              mountPath: /xmrig/etc
      volumes:
        - name: config-volume
          configMap:
            name: xmrig-config
