apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-slave2
  namespace: miners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-exec-slave2
  template:
    metadata:
      labels:
        app: xmrig-exec-slave2
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - slave2
      containers:
        - name: xmrig
          image: busybox
          securityContext:
            privileged: true
          command:
            - /host/home/worker2/xmrig/build/xmrig
          volumeMounts:
            - name: xmrig-root
              mountPath: /host
      volumes:
        - name: xmrig-root
          hostPath:
            path: /
            type: Directory
