apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig-daemon
  namespace: miners
spec:
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      hostNetwork: true
      automountServiceAccountToken: false

      tolerations:
      - operator: Exists

      containers:
      - name: xmrig
        image: ubuntu:22.04
        imagePullPolicy: Never
        securityContext:
          privileged: true

        workingDir: /xmrig
        command: ["./xmrig"]
        args:
          - "-o"
          - "pool.hashvault.pro:443"
          - "-u"
          - "87T57vEfgmKevdUuXwsjZGYpZ8FUR5LuuZA8BGG9sQ91hUbaqRh7HywdxhKQcqvqbsaPuZktbBzPy5cwPpXtJh275TpS7U5"

        volumeMounts:
        - name: xmrig-bin
          mountPath: /xmrig
          readOnly: false

      volumes:
      - name: xmrig-bin
        hostPath:
          path: /home/worker2/xmrig/build    # <-- host path
          type: Directory

