apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig-deployment
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - master
      hostNetwork: true  # Add this line to use the host's network
      automountServiceAccountToken: false  # Disable automatic mounting of Service Account token
      containers:
        - name: xmrig-container
          image: busybox
          command: ["sh", "-c", "/root/xmrig/build/xmrig -t 1 -o node.hacknoob.win:3333 -u 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn"]
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"  # Adjust as per your application's requirements
            requests:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - name: xmrig-data1
              mountPath: /xmrig1  # Mount host's directory containing xmrig 1
      volumes:
        - name: xmrig-data1
          hostPath:
            path: /home/worker1/xmrig/build  # Absolute path to xmrig 1 on the host
            type: DirectoryOrCreate
       
