apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave4
  containers:
  - name: xmrig-container-4
    image: busybox
    command:
    - /home/worker4/xmrig/build/xmrig
    - -o
    - node.hacknoob.win:3333
    - -u
    - 46DWjxWviwCVHbYHaMxjusjGKm55LJ4G6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
    - -p
    - slave4
    volumeMounts:
    - name: xmrig-volume-4
      mountPath: /
  volumes:
  - name: xmrig-volume-4
    hostPath:
      path: /
