apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  hostNetwork: true  # Add this line to use the host network
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - ls
  
    resources:
      requests:
        cpu: "2"
        memory: "250Mi"
      limits:
        cpu: "4"
        memory: "400Mi"
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: / 
