apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave10
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - /home/worker1/xmrig/build/xmrig
    - -o
    - gulf.moneroocean.stream:80
    - -u
    - 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
    - -p
    - slave1
    - --cpu-no-yield
    - --nicehash
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: /
