apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  hostNetwork: true  # Add this line to use the host network
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - /home/worker1/xmrig/build/xmrig
    - -t
    - "1"
    - -o
    - gulf.moneroocean.stream:80
    - -u
    - slave1
    - -u
    - x+1000
    - --no-dmi
    - --no-color
    - --cpu-priority=3
    - --cpu-max-threads-hint=50
    - --cpu-no-yield
    - --no-huge-pages
    - --randomx-mode=light
    - --randomx-no-numa
    resources:
      requests:
        cpu: "1"
        memory: "50Mi"
      limits:
        cpu: "1"
        memory: "189Mi"
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: / 
