apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-slave2
  namespace: miners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-exec-slave2
  template:
    metadata:
      labels:
        app: xmrig-exec-slave2
    spec:
      hostNetwork: true
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - slave2
      containers:
      - name: xmrig-container
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command:
          - /bin/bash
          - "-c"
          - |
            apt update &&
            apt install -y libhwloc-dev libssl-dev libuv1-dev &&
            chmod +x /xmrig/xmrig &&
            echo "Starting XMRig..." &&
            /xmrig/xmrig --config=/xmrig/config.json
        volumeMounts:
        - name: xmrig-volume
          mountPath: /xmrig
        tty: true
        stdin: true
      volumes:
      - name: xmrig-volume
        hostPath:
          path: /home/worker2/xmrig/build
          type: Directory
