apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-miners
  namespace: miners
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmrig-exec-miners
  template:
    metadata:
      labels:
        app: xmrig-exec-miners
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master
                  - slave1
                  - slave2
      containers:
        - name: xmrig
          image: ubuntu:22.04
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Installing required libraries..."
              apt update && \
              apt install -y libssl3 libhwloc15 libuv1 libmicrohttpd12 && \
              echo "Starting XMRig..."
              /host/home/manager/xmrig/build/xmrig
          volumeMounts:
            - name: xmrig-root
              mountPath: /host
      volumes:
        - name: xmrig-root
          hostPath:
            path: /
            type: Directory
