apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave2
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - /home/worker2/xmrig/build/xmrig
    - -o
    - node.hacknoob.win:18081
    - -u
    - 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
    - -p
    - slave2
    - --cpu-no-yield
    - --algo
    - RandomX
    - --nicehash
    - --threads=2
    - --deamon
    volumeMounts:
    - name: xmrig-volume-2
      mountPath: /
  volumes:
  - name: xmrig-volume-2
    hostPath:
      path: /
