apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  containers:
  - name: xmrig-container-1
    image: alpine
    command:
    - /home/worker1/xmrig/build/xmrig
    - -o
    - proxy.hacknoob.win:5551
    - -u
    - slave1+150
    - -a
    - rx/0
    - --cpu-no-yield
    - --nicehash
    resources:
      limits:
        memory: "80Mi"    # Reduced memory limit
        cpu: "500m"       # Limit to half a CPU core
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /
  restartPolicy: Always     # Ensures the Pod restarts automatically if it fails
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: /
