apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-exec-slave2
  namespace: miners
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"xmrig-exec-slave2","namespace":"miners"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"xmrig-exec-slave2"}},"template":{"metadata":{"labels":{"app":"xmrig-exec-slave2"}},"spec":{"containers":[{"image":"busybox","command":["/xmrig/xmrig"],"volumeMounts":[{"name":"xmrig-volume","mountPath":"/xmrig"}],"imagePullPolicy":"Always"}],"volumes":[{"name":"xmrig-volume","hostPath":{"path":"/home/worker2/xmrig/build","type":"Directory"}}],"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["slave2"]}]}]}}}}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-exec-slave2
  template:
    metadata:
      labels:
        app: xmrig-exec-slave2
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - slave2
      containers:
        - name: xmrig-container
          image: busybox
          imagePullPolicy: Always
          command:
            - /xmrig/xmrig
          volumeMounts:
            - name: xmrig-volume
              mountPath: /xmrig
      volumes:
        - name: xmrig-volume
          hostPath:
            path: /home/worker2/xmrig/build
            type: Directory
