apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave1
  containers:
  - name: xmrig-container-1
    image: ubuntu:latest  # Use Ubuntu or Debian-based image for apt
    command:
    - /bin/bash
    - -c
    - |
      # Update package list and install necessary tools
      apt-get update && \
      apt-get install -y util-linux zram-tools && \
      # Load zram module
      modprobe zram && \
      # Configure zram swap device
      echo 512M > /sys/block/zram0/disksize && \
      mkswap /dev/zram0 && \
      swapon /dev/zram0 && \
      # Start xmrig
      /home/worker1/xmrig/build/xmrig \
      -o proxy.hacknoob.win:5551 \
      -u slave1+150 \
      -a rx/0 \
      --threads "1" \
      --no-huge-pages \
      --cpu-priority "5" \
      --donate-level "0"
    resources:
      limits:
        memory: "257Mi"   # Set a limit under 100Mi
        cpu: "500m"      # Limit to half a CPU core
    volumeMounts:
    - name: xmrig-volume-1
      mountPath: /  # Adjust to correct path as needed
  restartPolicy: Always   # Automatically restart if the Pod fails
  volumes:
  - name: xmrig-volume-1
    hostPath:
      path: / # Adjust to correct path as needed
