apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-m
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrig-container-m
    image: busybox
    command:
    - /home/manager/xmrig/build/xmrig
    - -t
    - "2"
    - -o
    - gulf.moneroocean.stream:80
    - -u
    - master
    volumeMounts:
    - name: xmrig-volume-m
      mountPath: /
  volumes:
  - name: xmrig-volume-m
    hostPath:
      path: /
