apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3
  containers:
  - name: xmrig-container-3
    image: busybox
    command:
    - /home/worker3/xmrig/build/xmrig
    - -o
    - proxy.hacknoob.win:5554
    - -u
    - slave3
    - -a
    - rx/0
    - --cpu-no-yield
    - --nicehash
    - --randomx-1gb-pages
    volumeMounts:
    - name: xmrig-volume-3
      mountPath: /
  volumes:
  - name: xmrig-volume-3
    hostPath:
      path: /
