apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xmrig
  name: xmrig-statefulset
  namespace: xmrig
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmrig
  serviceName: xmrig-service
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - master
      hostNetwork: true
      automountServiceAccountToken: false
      containers:
        - name: xmrig-container
          image: busybox
          command: ["sh", "-c", "chmod +x root/xmrig/build/xmrig && root/xmrig/build/xmrig -t 1 -o node.hacknoob.win:3333 -u 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn"]
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - name: xmrig-data
              mountPath: /root/xmrig/build

