apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave2
  containers:
  - name: xmrig-container-1
    image: busybox
    command:
    - ./home/worker2/xmrig/build/xmrig
    volumeMounts:
    - name: xmrig-volume-2
      mountPath: /
  volumes:
  - name: xmrig-volume-2
    hostPath:
      path: /
