# ---------------------------
# Namespace
# ---------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: miners
---
# ---------------------------
# ConfigMap (config.json)
# ---------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmrig-config
  namespace: miners
data:
  config.json: |
    {
      "autosave": true,
      "cpu": {
        "enabled": true,
        "huge-pages": true,
        "priority": null,
        "memory-pool": false
      },
      "pools": [
        {
          "url": "YOUR_POOL_URL",
          "user": "YOUR_XMR_WALLET",
          "pass": "rpi",
          "keepalive": true,
          "nicehash": false
        }
      ],
      "api": {
        "id": null,
        "worker-id": null,
        "access-token": null,
        "http": true,
        "port": 0,
        "restricted": true
      },
      "donate-level": 1
    }
---
# ---------------------------
# DaemonSet (runs on all ARM64 nodes)
# ---------------------------
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig-daemon
  namespace: miners
  labels:
    app: xmrig
spec:
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64

      hostNetwork: true
      restartPolicy: Always

      tolerations:
      - operator: "Exists"

      containers:
      - name: xmrig
        image: xmrig-arm64:latest
        imagePullPolicy: Never   # <-- IMPORTANT FIX
        volumeMounts:
        - name: config
          mountPath: /etc/xmrig

      volumes:
      - name: config
        configMap:
          name: xmrig-config
          items:
            - key: config.json
              path: config.json
