---
version: '3.4'
networks:
  p2pool:
    driver: bridge
volumes:
  p2pool: 
    name: p2pool

  monero:
    name: monero

services:
  p2pool:
    image: p2pool:latest
    build: ../
    container_name: p2pool-p2pool
    networks:
      - p2pool
    privileged: true
    ports:

      - 37888:37888/tcp


    volumes:
      - p2pool:/home/p2pool/.p2pool:rw
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw

    depends_on:
      - monero

    restart: unless-stopped
    command: >-

      --host monero

      --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
      --loglevel 3



      --local-api
      --data-api /home/p2pool/.p2pool






