apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2pool-server
  namespace: p2pool
spec:
  project: default

  source:
    repoURL: https://github.com/d3ceiver/p2pool.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: p2poolapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
    automated:
      selfHeal: true
      prune: true
   
  spec:
    replicas: 1
    affinity:
          topologyKey: "kubernetes.io/hostname"
    containers:
    - image: pataquets/p2pool:latest
      name: p2pool






