apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crypto-miner
  name: crypto-miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-miner
  template:
    metadata:
      labels:
        app: crypto-miner
    spec:
      containers:
      - image: ghcr.io/sethforprivacy/simple-monerod:latest
        services:
        name: monerod
        restart: unless-stopped
      
    volumes:
      - bitmonero:/home/monero
    ports:
      - 18080:18080
      - 18084:18084
      - 18089:18089
    command: >-
      --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=18089
      --public-node --no-igd --enable-dns-blocklist --prune-blockchain
      --zmq-pub=tcp://0.0.0.0:18084 --in-peers=50 --out-peers=50   
