apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: p2pool
spec:
  containers:
  - image: arm64v8/alpine:3.15.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
