---
version: '3.4'

networks:
  p2pool:
    driver: bridge

volumes:
  p2pool: 

    name: p2pool



  monero:
    name: monero


services:
  p2pool:
    image: p2pool:latest
    build: ../
    container_name: p2pool-p2pool
    networks:
      - p2pool
    privileged: true
    ports:

      - 37888:37888/tcp


    volumes:
      - p2pool:/home/p2pool/.p2pool:rw
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw

    depends_on:
      - monero

    restart: unless-stopped
    command: >-

      --host monero

      --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
      --loglevel 3



      --local-api
      --data-api /home/p2pool/.p2pool




  monero:
    image: monero:latest
    build:
      context: monero
      args:
        - MONERO_GIT_TAG=latest
    container_name: p2pool-monero
    networks:
      - p2pool
    ports:
      - 18080:18080/tcp

    volumes:
      - monero:/home/monero/.bitmonero:rw
      - /dev/null:/home/monero/.bitmonero/bitmonero.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    restart: unless-stopped
    command: >-
      --zmq-pub tcp://74.56.241.2:18083
      --disable-dns-checkpoints
      --enable-dns-blocklist
      --out-peers 16
      --in-peers 32
      --add-priority-node=nodes.hashvault.pro:18080
      --add-priority-node=p2pmd.xmrvsbeast.com:18080
      --non-interactive
      --p2p-bind-ip=0.0.0.0
      --p2p-bind-port=18080
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=18081
      --restricted-rpc
      --confirm-external-bind
      --log-level=0

      --prune-blockchain





      --fast-block-sync=1

