apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-server
  namespace: p2pool 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy: {}
  template:
    metadata:
      labels:
        app: p2pool-s
    spec:
      affinity:
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: sethsimmons/p2pool
        name: p2pool
        command: 
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "1"      
        volumeMounts:
        - name: config-volume
          mountPath: /xmrig/etc
      volumes:
      - name: config-volume
        configMap:
          name: xmrig-config





