apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2poolserver
  namespace: p2pool 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
 
    spec:
      affinity:
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: pataquets/p2pool:latest
        name: p2pool
       
      





