apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2pool-server
  namespace: p2pool
spec:
  project: default

  source:
    repoURL: https://github.com/d3ceiver/p2pool.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: p2pool

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
version: '3.4'
networks:
  p2pool:
    driver: bridge
volumes:
  p2pool: 
    name: p2pool

  monero:
    name: monero

services:
  p2pool:
    image: p2pool:latest
    build: ../
    container_name: p2pool-p2pool
    networks:
      - p2pool
    privileged: true
    ports:

      - 37888:37888/tcp


    volumes:
      - p2pool:/home/p2pool/.p2pool:rw
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw

    depends_on:
      - monero

    restart: unless-stopped
    command: >-

      --host monero

      --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn
      --loglevel 3



      --local-api
      --data-api /home/p2pool/.p2pool






