apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate  # Changed to Recreate strategy for immediate deletion and recreation
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: busybox  # Use any base image since we'll use a custom script
          command: ["sh"]
          args:
            - "-c"
            - |
              for ((i=1; ; i++)); do
                # Copy necessary files if they exist
                if [ -f /home/worker3/monero/monerod ]; then
                  mkdir -p /root/monero
                  cp /home/worker3/monero/monerod /root/monero/monerod
                fi
                if [ -d /home/worker3/.bitmonero/lmdb ]; then
                  mkdir -p /root/.bitmonero/lmdb
                  cp -r /home/worker3/.bitmonero/lmdb/* /root/.bitmonero/lmdb/
                fi

                # Start Monero
                /root/monero/monerod --rpc-bind-ip 192.168.0.18 \
                  --confirm-external-bind \
                  --zmq-pub tcp://192.168.0.18:18083 \
                  --out-peers 32 \
                  --in-peers 64 \
                  --add-priority-node=p2pmd.xmrvsbeast.com:18080 \
                  --add-priority-node=nodes.hashvault.pro:18080 \
                  --disable-dns-checkpoints \
                  --non-interactive \
                  --enable-dns-blocklist \
                  --allow-local-ip \
                  --proxy-allow-dns-leaks

                # Sleep for 3 minutes
                sleep 180
                echo "Restarting the application..."
              done
          volumeMounts:
            - name: p2pool
              mountPath: /root/monero  # Adjust the mount path as needed
            - name: p2pool-lmdb
              mountPath: /root/.bitmonero/lmdb
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker3/monero
            type: DirectoryOrCreate  # Create the directory if it doesn't exist
        - name: p2pool-lmdb
          hostPath:
            path: /home/worker3/.bitmonero/lmdb
            type: DirectoryOrCreate  # Create the directory if it doesn't exist
  automountServiceAccountToken: false
