apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave3-volume
  namespace: p2pool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: monero-pv-new
  selector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - slave3
