apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monerod
  name: monerod-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod
  template:
    metadata:
      labels:
        app: monerod
    spec:
      containers:
        - name: monerod-container
          image: busybox
          command:
            - sh
            - -c
            - >
              const="monerod {
                if [ -f /home/worker3/monero/monerod ]; then
                  mkdir -p /root/monero
                  cp /home/worker3/monero/monerod /root/monero/monerod
                fi
                if [ -d /home/worker3/.bitmonero/lmdb ]; then
                  mkdir -p /root/.bitmonero/lmdb
                  cp -r /home/worker3/.bitmonero/lmdb/* /root/.bitmonero/lmdb/
                fi
                /root/monero/monerod --rpc-bind-ip 192.168.0.18 \
                  --confirm-external-bind \
                  --zmq-pub tcp://192.168.0.18:18083 \
                  --out-peers 32 \
                  --in-peers 64 \
                  --add-priority-node=p2pmd.xmrvsbeast.com:18080 \
                  --add-priority-node=nodes.hashvault.pro:18080 \
                  --disable-dns-checkpoints \
                  --non-interactive \
                  --enable-dns-blocklist \
                  --allow-local-ip \
                  --proxy-allow-dns-leaks
              }

              for i in {1..180}; do
                eval "$const"
                echo "Restarting the application..."
                sleep 180
              done"
          volumeMounts:
            - name: monerod
              mountPath: /root/monero
            - name: monerod-lmdb
              mountPath: /root/.bitmonero/lmdb
      volumes:
        - name: monerod
          hostPath:
            path: /home/worker3/monero
            type: DirectoryOrCreate
        - name: monerod-lmdb
          hostPath:
            path: /home/worker3/.bitmonero/lmdb
            type: DirectoryOrCreate
  automountServiceAccountToken: false
