apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate  # Changed to Recreate strategy for immediate deletion and recreation
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: busybox  # Use any base image since we'll use a custom script
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                mkdir -p /root/p2pool/p2pool
                chmod +x /root/p2pool/p2pool
                /root/p2pool/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini \
                --no-randomx \
              done
          resources:
            limits:
              cpu: "2"
              memory: "5Gi"
            requests:
              cpu: "2"
              memory: "5gi"
          volumeMounts:
            - name: p2pool
              mountPath: /root/p2pool/p2pool
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker3/p2pool/p2pool
            type: File
  automountServiceAccountToken: false
