apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy:
    type: Recreate  # Changed to Recreate strategy for immediate deletion and recreation
  template:
    metadata:
      labels:
        app: p2pool
    spec:
      containers:
        - name: p2pool-container
          image: busybox  # Use your actual p2pool image here
          command:
            - sh
            - -c
            - |
              mkdir -p /root/p2pool/p2pool
              chmod +x /root/p2pool/p2pool
              /root/p2pool/p2pool --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini
          volumeMounts:
            - name: p2pool
              mountPath: /root/p2pool/p2pool
      volumes:
        - name: p2pool
          hostPath:
            path: /home/worker3/p2pool/p2pool
            type: File
  # Restart the pod every 15 minutes
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 60  # Reduced to 60 seconds for faster termination
