apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig
  namespace: xmrig 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: sethsimmons/p2pool
