apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: p2pool
  name: p2pool
  namespace: p2pool 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pool
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
       topologyKey: "kubernetes.io/hostname"
      containers:
      - image: sethsimmons/p2pool
