apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-deployment
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
      containers:
        - name: xmrig-container
          image: rcmelendez/xmrig:6.16.2
          command: ["xmrig"]
          args: ["-c", "/xmrig/etc/config.json"]
          resources:
            limits:
              cpu: "4"
              memory: "1Gi"  # Adjust memory as per your cluster's total available RAM
            requests:
              cpu: "2"
              memory: "500Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /xmrig/etc
      volumes:
        - name: config-volume
          configMap:
            name: xmrig-config
