apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        topologyKey: "kubernetes.io/hostname"
      containers:
      - image: rcmelendez/xmrig:6.16.2
        name: xmrig
        command: ["xmrig"]
        args: ["-c", "/xmrig/etc/config.json"]
        resources:
          limits:
            memory: "14Gi"
            cpu: "13"
          requests:
            memory: "8Gi"
            cpu: "9"
        volumeMounts:
        - name: config-volume
          mountPath: /xmrig/etc
      volumes:
      - name: config-volume
        configMap:
          name: xmrig-config
