apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-deployment
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - xmrig
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: xmrig-container
          image: rcmelendez/xmrig:6.16.2
          command: ["xmrig"]
          args: ["-c", "/xmrig/etc/config.json"]
          resources:
            limits:
              cpu: "13"
              memory: "14Gi"  # Adjust memory as per your cluster's total available RAM
            requests:
              cpu: "13"
              memory: "14Gi"
          volumeMounts:
            - name: config-volume
              mountPath: /xmrig/etc
      volumes:
        - name: config-volume
          configMap:
            name: xmrig-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmrig-config
  namespace: xmrig
data:
  config.json: |
    {
      "wallet": "46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn",
      "pool": "hacknoob.win:3333",
      "coin": "rx/0",
      "threads": 13,
      "background": false,
      "print-time": 60,
      "cpu-affinity": null
      // Add other xmrig configurations as needed
    }
