apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: rcmelendez/xmrig:6.16.2
        command: ["xmrig", "--config=/xmrig/etc/config.json"]
        resources:
          limits:
            cpu: "13000m"  # Assuming 13 CPUs, each with 1000m (milli CPUs)
            memory: "14Gi"  # 14.7GB RAM
          requests:
            cpu: "13000m"
            memory: "14Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /xmrig/etc
      volumes:
      - name: config-volume
        configMap:
          name: xmrig-config

