apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: arm64v8/mysql:5.7  # ARM-compatible image
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "your_database"
        - name: MYSQL_USER
          value: "your_username"
        - name: MYSQL_PASSWORD
          value: "your_password"
        ports:
        - containerPort: 3306
          name: mysql
