apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Port used by Nginx
      targetPort: 80     # Port exposed by the container
      nodePort: 30399    # NodePort exposed externally
  type: NodePort
