apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30399  # Specify the NodePort
  type: NodePort
