apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: slave2
      containers:
        - name: apache
          image: php:7.4-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /var/www/html
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Updating package lists..." && \
              apt update && apt install -y && apt full-upgrade -y && \
              
              echo "Installing nano and systemctl..." && \
              apt install -y nano systemctl && \

              echo "Installing SQLite3 and curl libraries..." && \
              apt-get install -y sqlite3 libsqlite3-dev curl && \

              echo "Enabling Apache proxy modules..." && \
              a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests && \

              echo "Downloading jQuery..." && \
              curl -o /var/www/html/jquery.min.js https://code.jquery.com/jquery-3.6.0.min.js && \

              echo "Downloading Framework7..." && \
              curl -o /var/www/html/framework7.bundle.min.js https://cdn.framework7.io/framework7.bundle.min.js && \

              echo "Restarting Apache server..." && \
              systemctl restart apache2 && \

              echo "Starting Apache in foreground..." && \
              apache2-foreground
      volumes:
        - name: website-content
          hostPath:
            path: /home/worker2/www/html
            type: Directory
