apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 1080  # Port exposed by the service
      targetPort: 1080  # Target port on the container
  type: NodePort  # This exposes the service externally
