apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
  labels:
    app: nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: nginx
        image: richarvey/nginx-php-fpm  # Nginx with PHP-FPM support
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /var/www/html  # Mount website files inside the container
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf  # Nginx config
          subPath: nginx.conf
        - name: fastcgi-snippet
          mountPath: /etc/nginx/snippets/fastcgi-php.conf  # Mount the fastcgi snippet
          subPath: fastcgi-php.conf
        env:
        - name: MYSQL_HOST
          value: "mysql-service"  # MySQL service name for the PHP connection
        - name: MYSQL_USER
          value: "your_username"
        - name: MYSQL_PASSWORD
          value: "your_password"
        - name: MYSQL_DATABASE
          value: "your_database"
      volumes:
      - name: website-content
        hostPath:
          path: /home/worker2/www/html  # Path to your website files on the host
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx-config  # Reference to the ConfigMap for Nginx config
      - name: fastcgi-snippet
        configMap:
          name: nginx-snippets-config  # Reference to ConfigMap for fastcgi-php.conf
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs only on slave2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
spec:
  selector:
    app: nginx-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

