apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of Nginx replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs only on slave2
      containers:
      - name: nginx
        image: nginx:latest  # Use the official Nginx image
        ports:
        - containerPort: 80  # Nginx listens on port 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf  # Mount the custom Nginx config
          subPath: nginx.conf                 # Ensure the correct file is mounted
        - name: website-content
          mountPath: /usr/share/nginx/html   # Nginx serves static files from this directory in the container
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config  # Reference to the ConfigMap you created
      - name: website-content
        hostPath:
          path: /home/worker2/www  # Path on the host where your website files are stored
          type: Directory
