apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs only on slave2
      containers:
      - name: nginx
        image: nginx:alpine  # Using Nginx as the web server
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: /usr/share/nginx/html  # Nginx's default directory for HTML
      volumes:
      - name: website-volume
        hostPath:
          path: /home/worker2/www/html  # Path on the host machine

