apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80            # Port used by Apache to forward traffic
      targetPort: 80       # Nginx's container port
      nodePort: 30399      # NodePort exposed externally (can be any available port)
  type: NodePort           # Exposes the service on a NodePort
