apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of Nginx replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Use the official Nginx image
        ports:
        - containerPort: 80  # Nginx listens on port 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html  # Mount the host directory to the default Nginx directory
      volumes:
      - name: website-content
        hostPath:
          path: /home/worker2/www/html  # Mount the host's html directory
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs only on slave2
