apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: slave2
      containers:
        - name: apache
          image: php:7.4-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /var/www/html
          # Command to install packages and start Apache
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install -y sqlite3 libsqlite3-dev php-sqlite3 && \
              apache2-foreground
      volumes:
        - name: website-content
          hostPath:
            path: /home/worker2/www/html
            type: Directory
