apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: slave2
      containers:
        - name: apache
          image: php:7.4-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /var/www/html
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && \
              apt install nano -y && \
              apt install systemctl -y && \
              a2enmod proxy && \
              a2enmod proxy_http && \
              a2enmod proxy_balancer && \
              a2enmod lbmethod_byrequests && \
              apt-get install -y sqlite3 libsqlite3-dev curl && \
              # Download jQuery and Framework7
              curl -o /var/www/html/jquery.min.js https://code.jquery.com/jquery-3.6.0.min.js && \
              curl -o /var/www/html/framework7.bundle.min.js https://cdn.framework7.io/framework7.bundle.min.js && \
              systemctl restart apache2 && \
              apache2-foreground
      volumes:
        - name: website-content
          hostPath:
            path: /home/worker2/www/html
            type: Directory
