apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs only on slave2
      containers:
      - name: website
        image: nginx:alpine  # Using Nginx as the web server
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: /usr/share/nginx/html  # Nginx's default directory for HTML
      volumes:
      - name: website-volume
        hostPath:
          path: /home/worker2/www/html  # Path on the host machine
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP  # Changed to ClusterIP for internal access only

