apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: slave2
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: website-content
          hostPath:
            path: /home/worker2/www
            type: Directory
