apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 30399  # Port exposed by the service
      targetPort: 80  # Target port on the container
  type: NodePort  # This exposes the service externally
