apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: website-content
          hostPath:
            path: /home/worker2/www  # Path on the host where your website files are stored
            type: Directory

