apiVersion: v1
kind: Service
metadata:
  name: monerod-service0
  namespace: default
spec:
  selector:
    app: monerod
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  type: NodePort  # Change to LoadBalancer if you are using a cloud provider that supports it
