apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monerod-pvc
  namespace: p2pool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: monerod-storageclass
  # Add node affinity to select 'slave3' node
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - slave3
