apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monerod
  name: monerod-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monerod
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave3
      containers:
        - name: monerod-container
          image: busybox
          command: ["sh"]
          args:
            - "-c"
            - |
              mkdir -p /root/monerod
              chmod +x /root/monerod
              /root/monerod --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini --no-randomx
          resources:
            limits:
              cpu: "2"
              memory: "5Gi"
            requests:
              cpu: "2"
              memory: "5Gi"
          volumeMounts:
            - name: monerod
              mountPath: /root/monerod
      volumes:
        - name: monerod
          hostPath:
            path: /home/worker3/monero
            type: DirectoryOrCreate
      securityContext:  # Example security context for privileged access
        privileged: true
  automountServiceAccountToken: false
