apiVersion: apps/v1
kind: Deployment
metadata:
  name: monerod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod-app
  template:
    metadata:
      labels:
        app: monerod-app
    spec:
      containers:
        - name: monerod-container
          image: your-monero-image
          command:
            - sh
            - -c
            - |
              mkdir -p /root/.bitmonero/
              cp /path/to/file/monero/monerod /root/monerod
              cp -r /path/to/file/.bitmonero/* /root/.bitmonero/
              /root/monerod
          volumeMounts:
          - name: volv
            mountPath: /data
          ports:
          - containerPort: 80
   volumes:
   - name: volv
     persistentVolumeClaim:
      claimName: local-path-pvc
          
