apiVersion: v1
kind: Pod
metadata:
  name: monero-pod
  namespace: p2pool
spec:
  containers:
    - name: monero-container
      image: busybox
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          cp /data/monero/monerod /root/monerod
          cp -r /data/.bitmonero/lmdb/* /root/.bitmonero/lmdb/
          /root/monerod
      volumeMounts:
        - name: monero-data
          mountPath: /data
  volumes:
    - name: monero-data
      persistentVolumeClaim:
        claimName: monero-pvc
