apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monerod-pvc
  namespace: p2pool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: monerod-storageclass
