apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monerod
  name: monerod-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod
  strategy:
    type: Recreate  # Changed to Recreate strategy for immediate deletion and recreation
  template:
    metadata:
      labels:
        app: monerod
    spec:
      nodeSelector:  # Added nodeSelector for node affinity
        kubernetes.io/hostname: slave3  # Specify the node 'slave3'
      containers:
        - name: monerod-container
          image: busybox  # Use any base image since we'll use a custom script
          command: ["sh"]
          args:
            - "-c"
            - |
              while true; do
                /home/worker3/monerod --host 192.168.0.18 --wallet 46DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn --mini \
                --no-randomx
              done
          resources:
            limits:
              cpu: "2"
              memory: "5Gi"
            requests:
              cpu: "2"
              memory: "5Gi"
  automountServiceAccountToken: false

