apiVersion: v1
kind: Pod
metadata:
  name: monero-pod
  namespace: p2pool
spec:
  containers:
    - name: monero-container
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /worker3/.bitmonero/lmdb/
          cp /monero/monerod /worker3/monero/monerod
          cp -r /.bitmonero/lmdb/* /worker3/.bitmonero/lmdb/
          chmod +x /worker3/monero/monerod  # Ensure the monerod executable is executable
          /root/monerod --rpc-bind-ip 192.168.0.188 \
            --confirm-external-bind \
            --zmq-pub tcp://192.168.0.188:18083 \
            --out-peers 32 \
            --in-peers 64 \
            --add-priority-node=p2pmd.xmrvsbeast.com:18080 \
            --add-priority-node=nodes.hashvault.pro:18080 \
            --disable-dns-checkpoints \
            --enable-dns-blocklist \
            --allow-local-ip \
            --proxy-allow-dns-leaks
      volumeMounts:
        - name: monero-data
          mountPath: /data
  volumes:
    - name: monero-data
      persistentVolumeClaim:
        claimName: slave3-volume  # Updated claimName to match your PVC
  tolerations:
    - key: "node.kubernetes.io/disk-pressure"
      operator: "Exists"
      effect: "NoSchedule"
