apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monero
  name: monero-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monero
  template:
    metadata:
      labels:
        app: monero
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - slave3
      initContainers:
        - name: create-directory
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - sudo mkdir -p /root/.bitmonero/lmdb && sudo mkdir -p /root/monero/monerod
          volumeMounts:
            - name: worker3-volume
              mountPath: /root/.bitmonero
            - name: worker3-volume
              mountPath: /root/monero
      containers:
        - name: monero-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - sudo /root/monero/monerod --rpc-bind-ip 192.168.0.18 \
              --prune-blockchain \
              --confirm-external-bind \
              --zmq-pub tcp://192.168.0.18:18083 \
              --out-peers 32 \
              --in-peers 64 \
              --add-priority-node=p2pmd.xmrvsbeast.com:18080 \
              --add-priority-node=nodes.hashvault.pro:18080 \
              --disable-dns-checkpoints \
              --non-interactive \
              --enable-dns-blocklist \
              --allow-local-ip \
              --proxy-allow-dns-leaks
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "2"
              memory: "500Mi"
          volumeMounts:
            - name: worker3-volume
              mountPath: /root/.bitmonero
            - name: worker3-volume
              mountPath: /root/monero

