apiVersion: v1
kind: Pod
metadata:
  name: monerod-pod
  namespace: p2pool
spec:
  containers:
    - name: monerod-container
      image: monerobox/monerod
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          cp /data/monero/monerod /root/monerod
          cp -r /data/.bitmonero/* /root/.bitmonero/
          /root/monerod
      volumeMounts:
        - name: volv
          mountPath: /data
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: local-path-pvc
