apiVersion: apps/v1
kind: Deployment
metadata:
  name: monerod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod-app
  template:
    metadata:
      labels:
        app: monerod-app
    spec:
      containers:
        - name: monerod-container
          image: simple-monerod-docker
          command:
            - sh
            - -c
            - |
              mkdir -p /root/.bitmonero/
              cp /path/to/file/monero/monerod /root/monerod
              cp -r /path/to/file/.bitmonero/* /root/.bitmonero/
              /root/monerod
