apiVersion: v1
kind: Service
metadata:
  name: monerod-service
  namespace: p2pool
spec:
  selector:
    app: monerod
  ports:
    - protocol: TCP
      port: 18081
      targetPort: 18081
    - protocol: TCP
      port: 37889
      targetPort: 37889
    - protocol: TCP
      port: 37888
      targetPort: 37888
