apiVersion: v1
kind: Service
metadata:
  name: monerod-service3
  namespace: default
spec:
  selector:
    app: monerod
  ports:
    - protocol: TCP
      port: 18083
      targetPort: 18083
  type: NodePort  # Change to LoadBalancer if you are using a cloud provider that supports it
