apiVersion: v1
kind: Service
metadata:
  name: monerod-service1
  namespace: p2pool
spec:
  selector:
    app: monerod
  ports:
    - protocol: TCP
      port: 18081
      targetPort: 18081
  type: NodePort  # Change to LoadBalancer if you are using a cloud provider that supports it
