apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-pvc
  namespace: p2pool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: monero-pv-new
