apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monero
  name: monero-deployment
  namespace: p2pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monero
  template:
    metadata:
      labels:
        app: monero
      containers:
        - name: monero-container
          # container spec...
      volumes:
        - name: monero-volume
          persistentVolumeClaim:
            claimName: monero-pvc
