apiVersion: v1
kind: Service
metadata:
  name: terminal-service
  namespace: p2pool
spec:
  selector:
    app: monerod
  ports:
    - protocol: TCP
      port: 18083
      targetPort: 18083
      nodePort: 30083  # Choose an available NodePort
  type: NodePort
