apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-rotator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-rotator
  template:
    metadata:
      labels:
        app: profile-rotator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - master # Ensure the Pod runs only on the master node
      containers:
      - name: profile-rotator-container
        image: busybox
        command:
        - /bin/sh
        args:
        - "-c"
        - |
          while true; do
            for file in MoneroOcean.txt  MoneroOcean.txt HashVault.txt MoneroOcean.txt  NanoPool.txt MoneroOcean.txt P2pool.txt; do
              algo_name=$(basename $file .txt)
              echo "Switching algorithm to $algo_name"
              echo "Switching algorithm to $algo_name" >> /logs/switch.log
              cp /profiles/$file /config/config.json
              sleep 1800
            done
          done
        volumeMounts:
        - name: profiles
          mountPath: /profiles
        - name: config
          mountPath: /config
        - name: logs
          mountPath: /logs
      volumes:
      - name: profiles
        hostPath:
          path: /home/manager/xmrig-proxy/build/profiles
      - name: config
        hostPath:
          path: /home/manager/xmrig-proxy/build
      - name: logs
        hostPath:
          path: /home/manager/xmrig-proxy/logs
