apiVersion: v1
kind: Pod
metadata:
  name: xmrigproxy-exec
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  containers:
  - name: xmrigproxy-container
    image: busybox
    command:
    - /home/manager/xmrigproxy/xmrig-proxy
    volumeMounts:
    - name: xmrig-volume-mp
      mountPath: /
  volumes:
  - name: xmrig-volume-mp
    hostPath:
      path: /
