apiVersion: v1
kind: Pod
metadata:
  name: xmrigproxy-exec
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3
  hostNetwork: true          
  containers:
  - name: xmrigproxy-container
    image: busybox
    command: ["sh"]
    args:
    - "-c"
    - |
      while true; do
       /home/worker3/xmrig-proxy/build/xmrig-proxy -O piclusterfarm:PiclusterFarmbitconnect44
      done
    volumeMounts:
    - name: xmrig-volume-worker3p
      mountPath: /
  volumes:
  - name: xmrig-volume-worker3p
    hostPath:
      path: /
