apiVersion: v1
kind: Pod
metadata:
  name: xmrigproxy-exec
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3
  hostNetwork: true          
  containers:
  - name: xmrigproxy-container
    image: busybox
    command:
    - /home/worker3/xmrig-proxy/build/xmrig-proxy --rpc-login piclusterfarm:PiclusterFarmbitconnect44
    volumeMounts:
    - name: xmrig-volume-worker3p
      mountPath: /
  volumes:
  - name: xmrig-volume-worker3p
    hostPath:
      path: /
