apiVersion: v1
kind: Pod
metadata:
  name: xmrigproxy-exec
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master
  hostNetwork: true          
  containers:
  - name: xmrigproxy-container
    image: busybox
    command: ["sh"]
    args:
    - "-c"
    - |
      while true; do
       /home/manager/xmrig-proxy/build/xmrig-proxy --daemon --verbose  --donate-level=0 --userpass=piclusterfarm:PiclusterFarmbitconnect4446DWjxWviwCVHbYHaMxjusjGKm55LJmG6f3YTCJDmTf2RxCLfQRx22fSRELvwq36kY6iSGD5tiUsSQ4AsE8UFnWFBDd1Lzn 
      done
    volumeMounts:
    - name: xmrig-volume-worker3p
      mountPath: /
  volumes:
  - name: xmrig-volume-worker3p
    hostPath:
      path: /
